### ISSUE TITLE
[DEBUG] identity is required to be specified in options

### ISSUE THREAD

**Issue by yangs326** [twilio-labs/plugin-token#62]
[DEBUG] Error: identity is required to be specified in options
    at new AccessToken (/Users/mavis/.twilio-cli/node_modules/twilio/lib/jwt/AccessToken.js:28:19)
    at VoiceTokenGenerator.createToken (/Users/mavis/.twilio-cli/node_modules/@twilio-labs/plugin-token/src/helpers/accessToken.js:14:23)
    at VoiceTokenGenerator.run (/Users/mavis/.twilio-cli/node_modules/@twilio-labs/plugin-token/src/commands/token/voice.js:17:37)
    at async VoiceTokenGenerator._run (/Users/mavis/.twilio-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/usr/local/lib/node_modules/twilio-cli/node_modules/@oclif/core/lib/config/config.js:301:25)

**Comment by yangs326** [comment]
Issue solved using fix from https://github.com/twilio-labs/plugin-token/issues/61#issue-2234747723
