### ISSUE TITLE
https://github.com/twilio-labs/plugin-token/issues

### ISSUE THREAD

**Issue by Yashh3023** [twilio-labs/plugin-token#64]
» twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: "https://github.com/twilio-labs/plugin-token/issues"
 ›   Error: EEXIT: 1
 ›   Code: EEXIT

**Comment by cecilia314** [comment]
I got the same error. Here is the output of the debug option command: 

[DEBUG] Config File: /Users/ceci/.twilio-cli/config.json
[DEBUG] Using profile: Twilio test 1
[DEBUG] Found command "token:voice" plugin: @twilio-labs/plugin-token
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: "https://github.com/twilio-labs/plugin-token/issues"
[DEBUG] identity is required to be specified in options
[DEBUG] Error: identity is required to be specified in options
    at new AccessToken (/Users/ceci/.twilio-cli/node_modules/twilio/lib/jwt/AccessToken.js:28:19)
    at VoiceTokenGenerator.createToken (/Users/ceci/.twilio-cli/node_modules/@twilio-labs/plugin-token/src/helpers/accessToken.js:14:23)
    at VoiceTokenGenerator.run (/Users/ceci/.twilio-cli/node_modules/@twilio-labs/plugin-token/src/commands/token/voice.js:17:37)
    at async VoiceTokenGenerator._run (/Users/ceci/.twilio-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/opt/homebrew/Cellar/twilio/5.22.9/libexec/node_modules/@oclif/core/lib/config/config.js:301:25)
 ›   Error: EEXIT: 1
 ›   Code: EEXIT

**Comment by ShiftAuto** [comment]
exact same error as well. Anyone figure it out?
